# ================================
# Configuration générale 
# ================================
title: Silvia Federzoni
description: Ma page personnelle 
url: "https://sfederzoni.github.io"
baseurl: "/SilviaFederzoni"

# ================================
# Thème Jekyll 
# ================================
theme: minima

# ================================
# Layaout pour les pages 
# ================================
defaults:
  - scope:
      path: "" # layout pour toutes les pages 
    values:
      layout: "default" # layout utilisé par défaut 
  - scope:
      path: "cv.md" # layout pour la page du CV  
    values:
      layout: "cv" # layout utilisé pour la page du CV

# ================================
# Menu
# ================================
header_pages: 
- index.md
- publications.md
- cv.md
- cours.md
- contact.md

# ================================
# Plugins GitHub Pages autorisés
# ================================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ================================
# Sass (CSS) options
# ================================
sass:
  style: compressed
