# ================================
# Configuration générale 
# ================================
title: Silvia Federzoni
description: Ma page personnelle de Silvia Federzoni
url: "https://sfederzoni.github.io/SilviaFederzoni/"
baseurl: ""

# ================================
# Thème Jekyll 
# ================================
theme: cayman

# ================================
# Layaout pour les pages 
# ================================
defaults:
  - scope:
      path: "" # layout pour toutes les pages 
    values:
      layout: "default" # layout utilisé par défaut 
  - scope:
      path: "cv.md" # layout pour la page du CV  
    values:
      layout: "cv" # layout utilisé pour la page du CV

